/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        outfit: ['Outfit', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'Outfit', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        deep: 'var(--deep)',
        surface: 'var(--surface)',
        panel: 'var(--panel)',
        card: 'var(--card)',
        border: 'var(--border)',
        cyan: 'var(--cyan)',
        'cyan-dim': 'var(--cyan-dim)',
        amber: 'var(--amber)',
        'amber-dim': 'var(--amber-dim)',
        magenta: 'var(--magenta)',
        green: 'var(--green)',
        lime: 'var(--lime)',
        blue: 'var(--blue)',
        red: 'var(--red)',
        muted: 'var(--muted)',
        'input-bg': 'var(--input-bg)',
        'card-bg': 'var(--card-bg)',
        'card-border': 'var(--card-border)',
        'metric-bg': 'var(--metric-bg)',
        'tooltip-bg': 'var(--tooltip-bg)',
      },
      borderRadius: {
        DEFAULT: '16px',
        sm: '10px',
      },
      animation: {
        'pulse-dot': 'pulse 1.5s ease-in-out infinite',
        'twinkle': 'twinkle var(--dur, 3s) ease-in-out infinite alternate',
        'orb-float': 'orbFloat 8s ease-in-out infinite alternate',
        'float-a': 'floatA 6s ease-in-out infinite',
        'float-b': 'floatB 7s ease-in-out infinite',
        'float-c': 'floatC 8s ease-in-out infinite',
        'sun-spin': 'sunSpin 30s linear infinite',
        'petal-fall': 'petalFall var(--pdur, 8s) linear infinite',
        'cursor-blink': 'cursorBlink 0.6s step-end infinite',
      },
    },
  },
  plugins: [],
};
