const { z } = require('zod')

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().default(4000),
  DATABASE_URL: z.string().optional(),
  DB_CONNECTION_LIMIT: z.coerce.number().default(5),
  PG_POOL_MAX: z.coerce.number().default(3),
  PG_IDLE_TIMEOUT_MS: z.coerce.number().default(10_000),
  PG_CONNECTION_TIMEOUT_MS: z.coerce.number().default(30_000),
  APP_ORIGIN: z.string().optional(),
  JWT_SECRET: z.string().default('playwise-secret'),
  JWT_EXPIRES: z.string().default('7d'),
  ADMIN_EMAILS: z.string().optional(),
  ADMIN_SETUP_CODE: z.string().optional(),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  MICROSOFT_CLIENT_ID: z.string().optional(),
  MICROSOFT_CLIENT_SECRET: z.string().optional(),
  MICROSOFT_TENANT_ID: z.string().default('common'),
  APPLE_CLIENT_ID: z.string().optional(),
  APPLE_TEAM_ID: z.string().optional(),
  APPLE_KEY_ID: z.string().optional(),
  APPLE_PRIVATE_KEY: z.string().optional(),
  IGDB_CLIENT_ID: z.string().optional(),
  IGDB_CLIENT_SECRET: z.string().optional(),
  IGDB_CACHE_MS: z.coerce.number().default(1000 * 60 * 60 * 6),
  IGDB_TOP_GAMES_LIMIT: z.coerce.number().default(500),
  STARTGG_API_TOKEN: z.string().optional(),
  STARTGG_TOURNAMENT_LIMIT: z.coerce.number().default(80),
  ITAD_API_KEY: z.string().optional(),
  ITAD_COUNTRY: z.string().default('IN'),
  PRICE_CACHE_MS: z.coerce.number().default(1000 * 60 * 60 * 6),
  GEMINI_API_KEY: z.string().optional(),
  GEMINI_MODEL: z.string().default('gemini-2.5-flash'),
  EMAIL_PROVIDER: z.string().default('smtp'),
  EMAIL_FROM: z.string().optional(),
  EMAIL_REPLY_TO: z.string().optional(),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().default(587),
  SMTP_SECURE: z.coerce.boolean().default(false),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  PRICE_ALERT_JOB_INTERVAL_MS: z.coerce.number().default(5 * 60 * 1000),
  TOURNAMENT_JOB_INTERVAL_MS: z.coerce.number().default(60 * 1000),
  TOURNAMENT_SOON_WINDOW_MINUTES: z.coerce.number().default(30),
  NOTIFICATION_BATCH_LIMIT: z.coerce.number().default(200),
  SENTRY_DSN: z.string().optional(),
  SENTRY_ENVIRONMENT: z.string().optional(),
  SENTRY_TRACES_SAMPLE_RATE: z.coerce.number().default(0.15),
  API_RATE_LIMIT_MAX: z.coerce.number().default(180)
})

const env = envSchema.parse(process.env)

module.exports = { env }
